"""empty message

Revision ID: 24d8ab6a7af7
Revises: 5cb6340e46f3
Create Date: 2022-04-07 16:19:57.941207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24d8ab6a7af7'
down_revision = '5cb6340e46f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connection_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('connection_driver', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_devices_connection_driver'), ['connection_driver'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_connection_status'), ['connection_status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_connection_status'))
        batch_op.drop_index(batch_op.f('ix_devices_connection_driver'))
        batch_op.drop_column('connection_driver')
        batch_op.drop_column('connection_status')

    # ### end Alembic commands ###
