"""empty message

Revision ID: 5cb6340e46f3
Revises: 
Create Date: 2022-03-31 23:51:11.811731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb6340e46f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_ip', sa.Integer(), nullable=False),
    sa.Column('device_hostname', sa.String(length=50), nullable=True),
    sa.Column('device_vendor', sa.String(length=100), nullable=True),
    sa.Column('device_model', sa.String(length=100), nullable=True),
    sa.Column('device_os_version', sa.String(length=100), nullable=True),
    sa.Column('device_sn', sa.String(length=100), nullable=True),
    sa.Column('device_uptime', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_hostname'), 'devices', ['device_hostname'], unique=False)
    op.create_index(op.f('ix_devices_device_ip'), 'devices', ['device_ip'], unique=False)
    op.create_index(op.f('ix_devices_device_model'), 'devices', ['device_model'], unique=False)
    op.create_index(op.f('ix_devices_device_os_version'), 'devices', ['device_os_version'], unique=False)
    op.create_index(op.f('ix_devices_device_sn'), 'devices', ['device_sn'], unique=False)
    op.create_index(op.f('ix_devices_device_uptime'), 'devices', ['device_uptime'], unique=False)
    op.create_index(op.f('ix_devices_device_vendor'), 'devices', ['device_vendor'], unique=False)
    op.create_table('configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(length=20), nullable=True),
    sa.Column('device_config', sa.Text(), nullable=False),
    sa.Column('device_ip', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_ip'], ['devices.device_ip'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configs')
    op.drop_index(op.f('ix_devices_device_vendor'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_uptime'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_sn'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_os_version'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_model'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_ip'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_hostname'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
